### ISSUE TITLE
Rename isaacgym env loaders

### ISSUE THREAD

**Issue by juhannc** [Toni-SM/skrl#21]
The function `load_isaacgym_env_preview3` works with IsaacGym Preview 3 and 4, well, mostly, see #20.
It will probably also (mostly) work with the upcoming versions given all the work NVIDIA put into separating the envs from the `isaacgym` package.
Renaming `load_isaacgym_env_preview3` to something like `load_isaacgym_env_preview3_4` or `load_isaacgym_env_preview3_and_up`.

Thus, I'd propose a new naming scheme which is more clear for users of Preview 4 (and possible other upcoming previews).

My proposal is renaming `load_isaacgym_env_preview3` to `load_isaacgym_env_preview` and `load_isaacgym_env_preview2` to `load_isaacgym_env_preview_legacy`.

Obviously, combining the code of both functions into one which can handle all current and future preview release would be the easiest solution, for end-users that is.

I'd be happy to implement those changes but wanted to discuss it first.

Cheers 🎉

_PS: All this might change once IsaacGym is out of preview, or a future previews breaks everything again._

**Comment by Toni-SM** [comment]
Hi @JohannLange 

Many thanks for trying this library.

Yes, the `load_isaacgym_env_preview3` works with preview 4 too...

The support for Isaac Gym preview 4 is already implemented since the release of this preview (6 days ago) in the `develop` branch (https://github.com/Toni-SM/skrl/tree/develop/skrl/envs/torch)
You can find information in the documentation (`develop` branch: https://skrl.readthedocs.io/en/develop/modules/skrl.envs.isaac_gym.html). 

I generalized the `load_isaacgym_env_preview3` method and created the `load_isaacgym_env_preview4` (an alias of the previous one).

I was waiting for the Isaac Gym teams to make the announcement of the new preview version, to announce the **skrl support for Isaac Gym preview 4**. However. I am going to merge with the `main` branch today and communicate the update in the Forum (together with other improvements of the library)
